/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <unistd.h>
/* Header for class secrobotapp_AIImplementationA */

#ifndef _Included_AIImplementationA
#define _Included_AIImplementationA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     secrobotapp_AIImplementationA
 * Method:    RunImplementationA
 * Signature: (Lsecrobotapp/RobotControl;)V
 */
JNIEXPORT void JNICALL Java_AIImplementationA_RunImplementationA
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
